### ISSUE TITLE
Uncaught TypeError: this.list.selectList.selectNone is not a function

### ISSUE THREAD

**Issue by sdaza** [lexicalunit/atom-notes#13]
**Atom**: 1.20.0-beta5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.5
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.8.1

### Stack Trace

Uncaught TypeError: this.list.selectList.selectNone is not a function

```
At /Users/sdaza/.atom/packages/atom-notes/lib/notes-view.js:29

TypeError: this.list.selectList.selectNone is not a function
    at NotesView.show (/packages/atom-notes/lib/notes-view.js:29:26)
    at NotesView.toggle (/packages/atom-notes/lib/notes-view.js:42:43)
    at /packages/atom-notes/lib/atom-notes.js:108:88)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
  2x -1:16.4.0 core:move-up (input.hidden-input)
     -1:15.7.0 core:confirm (input.hidden-input)
     -1:10.2.0 command-palette:toggle (div.tool-panel.tree-view)
  2x -1:07.8.0 core:backspace (input.hidden-input)
     -1:04.9.0 core:confirm (input.hidden-input)
     -1:04.9.0 markdown-preview:toggle (div.tool-panel.tree-view)
     -0:49.5.0 command-palette:toggle (input.hidden-input)
     -0:47.3.0 core:confirm (input.hidden-input)
     -0:47.3.0 markdown-preview:toggle (input.hidden-input)
     -0:30.4.0 command-palette:toggle (input.hidden-input)
     -0:28.5.0 editor:consolidate-selections (input.hidden-input)
     -0:28.5.0 core:cancel (input.hidden-input)
     -0:16.6.0 command-palette:toggle (input.hidden-input)
     -0:14.4.0 core:move-down (input.hidden-input)
     -0:14 core:confirm (input.hidden-input)
     -0:14 atom-notes:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-notes 1.8.1 
autocomplete-bibtex 0.7.0 
autocomplete-python 1.10.2 
date 1.2.2 
document-outline 1.6.1 
Hydrogen 1.21.1 
language-latex 1.1.1 
language-r 0.4.2 
language-stata 0.4.0 
latex 0.46.0 
latex-completions 0.3.3 
latexer 0.3.0 
pdf-view 0.59.0 
platformio-ide-terminal 2.6.0 
print-atom 0.1.1 
project-manager 3.3.5 
python-autopep8 0.1.3 
python-indent 1.1.0 
r-exec 0.5.0 
script 3.15.0 
tasks 2.6.7 
todo-show 2.0.0 
wordcount 2.10.4 
```

**Comment by lexicalunit** [comment]
@sdaza Does this error happen for you every single time you try to bring up the notes view?

🤔 It's possible that somehow you've got the wrong version of [`atom-select-list`](https://github.com/atom/atom-select-list) installed. The `selectNone()` function is only available on [a branch I created](https://github.com/lexicalunit/atom-select-list/tree/lexicalunit/autocomplete) on my personal fork of the library. This branch has support for search auto completion, which includes the addition of the `selectNone()` function.

Can you verify that Atom has installed things correctly by running the following command from your terminal and reporting back the output, @sdaza:

```
grep -n selectNone ~/.atom/packages/atom-notes/node_modules/atom-select-list/src/select-list-view.js
```

The result I'm hoping to see is:

```
304:  selectNone () {
```

**Comment by sdaza** [comment]
I reinstalled atom and now it is working fine. Thanks!

**Comment by lexicalunit** [comment]
Good to hear! 🎉
