### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substring' of undefined

### ISSUE THREAD

**Issue by OmeGak** [lexicalunit/atom-notes#16]
[Enter steps to reproduce:]

1. Toggle Atom Notes.
2. Start typing and the uncaught error appears.

This happens inconsistently but often enough to make the package completely unusable. When it happens, the Atom Notes toggle palette stops working (not reacting to typing events, not reacting to arrow keys, not clickable).

**Atom**: 1.19.7 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.11.1

### Stack Trace

Uncaught TypeError: Cannot read property 'substring' of undefined

```
At /Users/omegak/.dotfiles/atom/atom.symlink/packages/atom-notes/lib/notes-view-list.js:287

TypeError: Cannot read property 'substring' of undefined
    at highlight (/packages/atom-notes/lib/notes-view-list.js:287:52)
    at NotesViewList.elementForItem (/packages/atom-notes/lib/notes-view-list.js:83:25)
    at Object.elementForItem (/packages/atom-notes/lib/notes-view-list.js:60:38)
    at /packages/atom-notes/node_modules/atom-select-list/src/select-list-view.js:185:33)
    at Array.map (native)
    at SelectListView.renderItems (/packages/atom-notes/node_modules/atom-select-list/src/select-list-view.js:181:23)
    at SelectListView.render (/packages/atom-notes/node_modules/atom-select-list/src/select-list-view.js:172:12)
    at updateSync (/packages/atom-notes/node_modules/etch/lib/component-helpers.js:99:34)
    at /packages/atom-notes/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/multi-wrap-guide/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
     -0:48.4.0 pane:show-previous-item (input.hidden-input)
  2x -0:47.7.0 core:move-down (input.hidden-input)
     -0:47.3.0 core:move-up (input.hidden-input)
     -0:46.8.0 core:move-right (input.hidden-input)
     -0:46.4.0 editor:select-to-previous-word-boundary (input.hidden-input)
  4x -0:46 core:move-right (input.hidden-input)
     -0:45.2.0 editor:newline (input.hidden-input)
     -0:44.6.0 core:backspace (input.hidden-input)
     -0:43.5.0 core:paste (input.hidden-input)
  3x -0:42.5.0 core:move-left (input.hidden-input)
     -0:42 intentions:highlight (input.hidden-input)
     -0:41.8.0 atom-notes:interlink (input.hidden-input)
     -0:07.4.0 atom-notes:toggle (input.hidden-input)
     -0:03.9.0 editor:delete-to-previous-word-boundary (input.hidden-input)
     -0:03.3.0 editor:consolidate-selections (input.hidden-input)
     -0:03.3.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-jinja2 0.6.0 
atom-notes 1.11.1 
blame 0.12.0 
build 0.68.0 
busy 0.7.0 
editorconfig 2.2.2 
emmet 2.4.3 
file-icons 2.1.11 
git-blame 1.2.2 
highlight-selected 0.13.1 
Hydrogen 1.21.1 
intentions 1.1.5 
language-babel 2.74.1 
language-docker 1.1.8 
language-gitignore 0.3.0 
language-haproxy 0.6.1 
language-ini 1.19.0 
language-latex 1.1.1 
language-log 1.8.0 
language-nginx 0.8.0 
language-nunjucks 4.1.0 
last-cursor-position 0.9.2 
latex 0.46.0 
line-jumper 0.14.1 
linter 2.2.0 
linter-docker 0.2.1 
linter-eslint 8.2.1 
linter-flake8 2.2.1 
linter-htmlhint 1.3.3 
linter-js-yaml 1.2.7 
linter-rubocop 2.1.1 
linter-sass-lint 1.7.6 
linter-shellcheck 1.4.6 
linter-ui-default 1.6.8 
MagicPython 1.0.12 
markdown-preview-plus 2.4.10 
minimap 4.29.6 
multi-wrap-guide 1.0.0 
package-sync 1.1.0 
pdf-view 0.59.0 
pinned-tabs 1.3.0 
project-manager 3.3.5 
ssh-config 0.12.0 
tab-control 0.6.10 
typewriter-scroll 1.0.0 
```

**Comment by lexicalunit** [comment]
Thank you for the report! I'll be releasing a fix for this shortly.

**Comment by lexicalunit** [comment]
Please try v1.11.2.

**Comment by OmeGak** [comment]
Seems to be working fine. Thanks for the quick fix!
