### ISSUE TITLE
Uncaught TypeError: doc.keywords.join is not a function

### ISSUE THREAD

**Issue by lakonis** [lexicalunit/atom-notes#23]
[Enter steps to reproduce:]

1. update to v1.15.1
2. restart Atom with opened tabs with atom-notes

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Ubuntu 16.04.3
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.15.1

### Stack Trace

Uncaught TypeError: doc.keywords.join is not a function

```
At /home/nicolas/.atom/packages/atom-notes/lib/notes-store.js:112

TypeError: doc.keywords.join is not a function
    at NotesStore.addDocument (/packages/atom-notes/lib/notes-store.js:112:30)
    at /packages/atom-notes/lib/notes-store.js:95:35)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/atom-notes/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/packages/atom-notes/node_modules/chokidar/index.js:238:5)
    at FSWatcher.NodeFsHandler._handleFile (/packages/atom-notes/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at /packages/atom-notes/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-notes 1.15.1 
autocomplete-bibtex 1.1.0 
broadcast 0.4.0 
git-plus 7.10.0 
language-atom-notes 0.2.3 
language-mediawiki 2.2.0 
markdown-document 0.2.1 
markdown-folder 0.5.0 
markdown-scroll-sync 2.1.2 
markdown-toc 0.4.2 
markdown-writer 2.7.3 
nvatom 0.11.0 
pandoc-convert 1.1.1 
project-viewer 1.2.5 
spell-check-test 0.77.5 
terminal-plus 0.14.5 
tidy-markdown 3.0.1 
wordcount 2.10.4 
xml-tools 0.2.1 
Zen 0.18.0 
```

**Comment by lexicalunit** [comment]
Added a guard to fix this issue and released it in `v1.15.2`. Thanks for the report!

**Comment by lakonis** [comment]
After update, I get the same "Uncaught TypeError: doc.keywords.join is not a function" : 
```
TypeError: doc.keywords.join is not a function
    at NotesStore.addDocument (~/.atom/packages/atom-notes/lib/notes-store.js:115:36)
    at FSWatcher.<anonymous> (~/.atom/packages/atom-notes/lib/notes-store.js:95:35)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at FSWatcher.<anonymous> (~/.atom/packages/atom-notes/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (~/.atom/packages/atom-notes/node_modules/chokidar/index.js:238:5)
    at FSWatcher.NodeFsHandler._handleFile (~/.atom/packages/atom-notes/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at FSWatcher.<anonymous> (~/.atom/packages/atom-notes/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

**Comment by lexicalunit** [comment]
Weird. The guard should have caught that. I made the guard more robust by testing if keywords is actually an array before calling `.join()` on it. If that doesn't fix it I'm not sure what will. Try `v1.15.3`.
