### ISSUE TITLE
Uncaught YAMLException: can not read a block mapping entry; a multiline key may not be an implici...

### ISSUE THREAD

**Issue by yanivdll** [lexicalunit/atom-notes#24]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.15.3

### Stack Trace

Uncaught YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 25, column 15:
    Think about it: all I had to do to get myself  ... 
                  ^

```
At /Users/ygilad/.atom/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:171

YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key at line 25, column 15:
    Think about it: all I had to do to get myself  ... 
                  ^
    at generateError (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:1046:9)
    at composeNode (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/packages/atom-notes/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at module.exports (/packages/atom-notes/node_modules/gray-matter/lib/parse.js:12:17)
    at parseMatter (/packages/atom-notes/node_modules/gray-matter/index.js:94:15)
    at matter (/packages/atom-notes/node_modules/gray-matter/index.js:46:10)
    at createDocument (/packages/atom-notes/lib/notes-store.js:33:14)
    at /packages/atom-notes/lib/notes-store.js:95:47)
    at emitTwo (events.js:106:13)
    at FSWatcher.emit (events.js:191:7)
    at /packages/atom-notes/node_modules/chokidar/index.js:196:15)
    at FSWatcher._emit (/packages/atom-notes/node_modules/chokidar/index.js:238:5)
    at FSWatcher.NodeFsHandler._handleFile (/packages/atom-notes/node_modules/chokidar/lib/nodefs-handler.js:275:10)
    at /packages/atom-notes/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

### Commands

```
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-notes 1.15.3 
atom-python-run 0.9.5 
python-debugger 0.2.0 
python-tools 0.6.9 
scroll-through-time 0.3.0 
which-key 0.3.3 
```

**Comment by lexicalunit** [comment]
Thanks for the bug report. I added some error handling around this feature which should hopefully resolve issues like this in the future. Also added you as a contributor. Please give version `v1.15.4` a try.
