### ISSUE TITLE
Uncaught Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by tthkbw** [lexicalunit/atom-notes#34]
I am pretty new to Atom and am using atom-notes as a replacement for NvAlt. I keep getting this error message. It happens every few minutes when working with files in my note directory. However, I have not been able to relate the failure to any particular action--it just seems to happen now and then.

I have not idea if this could be related or not, but the directory where my notes are stored is also used by DevonThink as an indexed directory, meaning that DevonThink may go out and index items in the directory when changes are made.

Any ideas?

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.17.1

### Stack Trace

Uncaught Error: EISDIR: illegal operation on a directory, read

```
At fs.js:682

Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:682:19)
    at tryReadSync (fs.js:480:20)
    at Proxy.fs.readFileSync (fs.js:517:19)
    at Proxy.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at createDocument (/packages/atom-notes/lib/notes-store.js:34:17)
    at /packages/atom-notes/lib/notes-store.js:82:29
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:539:13)
    at sub.native.onDidChange.events (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:464:64)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at NativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:325:24)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:133:13)
```

### Commands

```
  3x -0:35.2.0 blur (input.hidden-input)
     -0:34.9.0 core:confirm (input.hidden-input)
  3x -0:34.9.0 blur (input.hidden-input)
     -0:33.7.0 vim-mode-plus:move-up (input.hidden-input)
  3x -0:33.2.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:31.4.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:30.4.0 ex-mode:open (input.hidden-input)
  3x -0:30.4.0 blur (input.hidden-input)
     -0:30.1.0 core:confirm (input.hidden-input)
  3x -0:30.1.0 blur (input.hidden-input)
  3x -0:28.9.0 vim-mode-plus:move-to-previous-word (input.hidden-input)
     -0:27.2.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
     -0:26.5.0 vim-mode-plus:move-to-last-line (input.hidden-input)
     -0:23 vim-mode-plus:move-to-last-character-of-line (input.hidden-input)
     -0:19.5.0 fuzzy-finder:toggle-buffer-finder (input.hidden-input)
  8x -0:19.5.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-notes 1.17.1 
ex-mode 0.18.0 
github-web 1.1.0 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
minimap 4.29.8 
monokai 0.24.0 
pen-paper-coffee-syntax 0.14.9 
textmate-multimarkdown-syntax 0.1.0 
tool-bar 1.1.7 
tool-bar-markdown-writer 0.3.1 
unity-ui 2.1.11 
vim-mode-plus 1.32.0 
```

**Comment by lexicalunit** [comment]
Thanks @tthkbw, I'm able to re-create this bug now. Fixing now.

**Comment by lexicalunit** [comment]
Give v1.17.2 a try, should be fixed now. Thanks for the bug report!
