### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by alflanagan** [lexicalunit/atom-notes#4]
[Enter steps to reproduce:]

1. Install atom-notes (I used `apm install atom-notes`)
2. <kbd>ctrl</kbd>-<kbd>shift</kbd>-<kbd>p</kbd> and choose "Atom Notes: Interlink"
3. Note I did no setup of the package preferences.

**Atom**: 1.19.0-beta6 x64
**Electron**: 1.6.9
**OS**: "Fedora release
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.0.4

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /home/aflanagan/.atom/packages/atom-notes/lib/interlink.js:14

TypeError: Cannot read property 'getPath' of undefined
    at Object.openInterlink (/packages/atom-notes/lib/interlink.js:14:48)
    at /packages/atom-notes/index.js:30:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom-beta/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom-beta/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/usr/share/atom-beta/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/usr/share/atom-beta/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at SelectListView.didClickItem (/usr/share/atom-beta/resources/app/node_modules/atom-select-list/src/select-list-view.js:228:16)
    at ListItemView.onclick (/usr/share/atom-beta/resources/app/node_modules/atom-select-list/src/select-list-view.js:168:37)
    at ListItemView.didClick (/usr/share/atom-beta/resources/app/node_modules/atom-select-list/src/select-list-view.js:361:16)
```

### Commands

```
     -5:49.8.0 atom-notes:toggle (atom-pane.pane)
     -4:54.6.0 intentions:highlight (input.hidden-input)
     -4:51.8.0 markdown-preview:toggle (input.hidden-input)
     -1:23.8.0 atom-notes:toggle (input.hidden-input)
     -1:12 intentions:highlight (input.hidden-input)
     -1:11.1.0 markdown-preview:toggle (input.hidden-input)
     -0:21 command-palette:toggle (div.markdown-preview.native-key-bindings)
     -0:17.4.0 atom-notes:interlink (div.markdown-preview.native-key-bindings)
```

### Non-Core Packages

```
advanced-open-file 0.16.6 
atom-beautify 0.30.4 
atom-keyboard-macros 0.10.0 
atom-live-grammar-reload 0.8.0 
atom-notes 1.0.4 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
autocomplete-paths 1.0.5 
autocomplete-python 1.9.1 
busy-signal 1.4.3 
clipboard-plus 0.5.1 
custom-folds 1.9.4 
disable-keybindings 0.6.0 
django-templates 0.5.0 
editorconfig 2.2.2 
export-html 3.1.0 
file-icons 2.1.9 
flex-tool-bar 0.12.0 
go-plus 5.5.5 
grammar-mode 1.1.0 
Hydrogen 1.19.0 
hyperclick 0.1.3 
intentions 1.1.5 
js-hyperclick 1.11.0 
jumpy 3.1.3 
language-babel 2.68.0 
language-forth 0.2.3 
language-generic-config 1.3.0 
language-javascript-jsx 0.3.7 
language-markdown 0.25.1 
language-mips 0.3.0 
language-powershell 4.0.0 
language-svg 0.9.2 
last-cursor-position 0.9.2 
linter 2.2.0 
linter-coffeescript 1.0.0 
linter-eslint 8.2.1 
linter-gcc 0.7.1 
linter-jsonlint 1.3.0 
linter-less 2.6.0 
linter-phpcs 1.6.7 
linter-pycodestyle 2.0.2 
linter-pydocstyle 0.4.7 
linter-shellcheck 1.4.4 
linter-ui-default 1.6.3 
linter-xmllint 1.4.3 
MagicPython 1.0.11 
minimap 4.29.3 
minimap-git-diff 4.3.1 
minimap-linter 2.0.2 
open-unsupported-files 1.0.20 
php-integrator-annotations 1.2.0 
php-integrator-autocomplete-plus 1.6.0 
php-integrator-base 3.0.1 
php-integrator-navigation 1.2.1 
php-integrator-refactoring 1.4.1 
php-integrator-symbol-viewer 0.6.4 
postcss-sorting 2.10.0 
project-manager 3.3.5 
python-isort 0.0.7 
python-snippets 1.9.0 
python-tools 0.6.9 
python-yapf 0.14.0 
pythonic-atom 0.2.1 
script 3.15.0 
shell-it 0.2.1 
slickedit-select 1.6.2 
sort-lines 0.14.0 
split-diff 1.4.3 
terminal-plus 0.14.5 
tool-bar 1.1.0 
```

**Comment by lexicalunit** [comment]
Thanks for the ticket! This is a feature I personally don't use much so I'm not surprised a bug slipped through. We really need to have some spec tests for things like this. Fixed and released in v1.0.5.
