### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLocaleDateString' of undefined

### ISSUE THREAD

**Issue by rcraggs** [lexicalunit/atom-notes#41]
Started a search on an existing directory of markdown notes after switching the default notes directory.

**Atom**: 1.26.1 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.19.0

### Stack Trace

Uncaught TypeError: Cannot read property 'toLocaleDateString' of undefined

```
At /Users/rc305/.atom/packages/atom-notes/lib/notes-view-list.js:104

TypeError: Cannot read property 'toLocaleDateString' of undefined
    at NotesViewList.elementForItem (/packages/atom-notes/lib/notes-view-list.js:104:43)
    at Object.elementForItem (/packages/atom-notes/lib/notes-view-list.js:70:36)
    at listItems.items.map (/packages/atom-notes/lib/select-list-view.js:221:31)
    at Array.map (native)
    at SelectListView.renderItems (/packages/atom-notes/lib/select-list-view.js:217:35)
    at SelectListView.render (/packages/atom-notes/lib/select-list-view.js:201:12)
    at updateSync (/packages/atom-notes/node_modules/etch/lib/component-helpers.js:119:34)
    at /packages/atom-notes/node_modules/etch/lib/component-helpers.js:84:7
    at DefaultScheduler.performUpdates (/packages/atom-notes/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
     -0:33.4.0 settings-view:open (input.hidden-input)
     -0:18.3.0 core:close (input.hidden-input)
     -0:16.7.0 atom-notes:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-markboard 2.1.3 
atom-notes 1.19.0 
markdown-writer 2.7.3 
marked 0.1.10 
```

**Comment by lexicalunit** [comment]
@rcraggs give v1.19.1 a try.
