### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gbirke** [lexicalunit/atom-notes#47]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.1 x64
**Electron**: 2.0.4
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.19.2

### Stack Trace

Uncaught TypeError: Cannot convert undefined or null to object

```
At /Users/gabi/.atom/packages/atom-notes/lib/notes-store.js:13

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at isEmpty (/packages/atom-notes/lib/notes-store.js:13:17)
    at NotesStore.removeDocument (/packages/atom-notes/lib/notes-store.js:196:9)
    at /packages/atom-notes/lib/notes-store.js:103:14
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at NSFWNativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:167:24)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:276:18)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-jade 0.3.0 
atom-jinja2 0.6.0 
atom-notes 1.19.2 
build 0.70.0 
build-markdown 1.1.1 
busy 0.7.0 
busy-signal 1.4.3 
change-case 0.6.5 
cucumber 0.6.0 
cucumber-step 0.2.0 
dash 1.7.1 
docblockr 0.13.7 
editorconfig 2.2.2 
emmet 2.4.3 
highlight-line 0.12.0 
highlight-selected 0.13.1 
html-entitize 1.1.0 
intentions 1.1.5 
language-puppet 0.23.0 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
minimap 4.29.8 
php-twig 4.0.0 
tabs-to-spaces 1.0.5 
wordcount 3.0.0 
xml-formatter 0.11.0 
```

**Comment by lexicalunit** [comment]
Resolved in v1.19.3. Thanks for the report!
