### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, lstat '$ATOM_HOME/atom-notes/_mdwriter.cson'

### ISSUE THREAD

**Issue by raysewell** [lexicalunit/atom-notes#50]
[Enter steps to reproduce:]

1. I deleted a note file from the notes directory (the empty file kept showing up on my list of notes)
2. The error appeared shortly after I removed the file.

**Atom**: 1.28.2 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.19.4

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, lstat '/Users/rsewell/.atom/atom-notes/_mdwriter.cson'

```
At fs.js:1661

Error: ENOENT: no such file or directory, lstat '/Users/rsewell/.atom/atom-notes/_mdwriter.cson'
    at Proxy.realpathSync (fs.js:1661:15)
    at Proxy.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at NotesStore.removeDocument (/packages/atom-notes/lib/notes-store.js:199:20)
    at /packages/atom-notes/lib/notes-store.js:103:14
    at PathWatcher.onNativeEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:533:13)
    at sub.native.onDidChange.events (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:436:64)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:27:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:156:34)
    at NSFWNativeWatcher.onEvents (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:167:24)
    at handler (/Applications/Atom.app/Contents/Resources/app/src/path-watcher.js:276:18)
```

### Commands

```
     -9:11 editor:consolidate-selections (input.hidden-input)
     -9:11 core:cancel (input.hidden-input)
     -9:01.9.0 application:reopen-project (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-one-dark-ui)
     -3:41.1.0 application:open (input.hidden-input)
  3x -2:41.3.0 core:backspace (input.hidden-input)
     -1:30.5.0 markdown-preview-plus:toggle (input.hidden-input)
     -1:11.9.0 core:select-all (input.hidden-input)
     -1:11.6.0 core:backspace (input.hidden-input)
     -1:10.8.0 core:save (input.hidden-input)
     -0:59.9.0 core:select-all (input.hidden-input)
     -0:58.9.0 core:backspace (input.hidden-input)
     -0:57.9.0 core:save (input.hidden-input)
     -0:51 editor:consolidate-selections (input.hidden-input)
     -0:51 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
atom-notes 1.19.4 
ftp-remote-edit 0.12.12 
markdown-preview-plus 3.3.3 
markdown-writer 2.7.4 
pandoc-convert 1.1.1 
remote-sync 4.1.8 
rest-client 1.3.1 
sync-settings 0.8.6 
wordcount 3.0.0 
```

**Comment by lexicalunit** [comment]
My apologies, this is a bug I introduced earlier today when trying to fix a different bug.

**Comment by lexicalunit** [comment]
@raysewell Please give v1.19.5 a try.
