### ISSUE TITLE
Uncaught Error: EIO: i/o error, mkdir '~/googledrive/atom-notes'

### ISSUE THREAD

**Issue by onesentforth** [lexicalunit/atom-notes#51]
[Enter steps to reproduce:]

1. Start Atom.

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: GalliumOS 2.1
**Thrown From**: [atom-notes](https://github.com/lexicalunit/atom-notes) package 1.19.6

### Stack Trace

Uncaught Error: EIO: i/o error, mkdir '/home/jason/googledrive/atom-notes'

```
At /home/jason/.atom/packages/atom-notes/node_modules/mkdirp/index.js:90

Error: EIO: i/o error, mkdir '/home/jason/googledrive/atom-notes'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Function.sync (/packages/atom-notes/node_modules/mkdirp/index.js:71:13)
    at Proxy.makeTreeSync (/packages/atom-notes/node_modules/fs-plus/lib/fs-plus.js:385:23)
    at ensureNotesDirectory (/packages/atom-notes/lib/atom-notes.js:252:8)
    at /packages/atom-notes/lib/atom-notes.js:152:10
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-notes 1.19.6 
city-lights-syntax 1.1.8 
dark-nebula-syntax 0.1.1 
date 2.1.0 
file-icons 2.1.24 
language-hugo 0.5.1 
language-markdown 0.26.0 
nebula-syntax 0.4.5 
nebula-ui 0.9.3 
night-owl-syntax 1.0.1 
night-owl-ui 1.0.0 
nucleus-dark-ui 0.12.3 
pandoc-convert 1.1.1 
spell-check-project 0.7.0 
wordcount 3.0.0 
```

**Comment by lexicalunit** [comment]
Thanks for the report, I think v1.19.7 should fix this!
